### ISSUE TITLE
Frames of some videos in the charades cannot be read

### ISSUE THREAD

**Issue by enlikahlil** [sangminwoo/Explore-And-Match#10]
Thanks for your meaningful work. When I tried to get frames per video, I noticed some of frames folders were empty, it happened to num_frames of 16/32/64/126/256 all. It looks like there were some problems when reading the video frames of charades with opencv, would you kindly give us some advice? And I downloaded the original size of charades(55GB), which version of charades did you use?Thank you!

**Comment by amrita058** [comment]
i have the same issue on the scaled (480p, 13GB) dataset.
