### ISSUE TITLE
Get CLIP Feature for Charades

### ISSUE THREAD

**Issue by aries-young** [sangminwoo/Explore-And-Match#2]
I find the following code in clip_encoder.py. There are train.json and text.json required for charades. But in [jiyanggao](https://github.com/jiyanggao)/[TALL](https://github.com/jiyanggao/TALL), only charades_sta_train/test.txt are provided. How do you extract the CLIP features for charades ? Could you provide the features used in LVTR by Google Drive or Box ? And will you kindly provide some detailed description of the document organization of your datasets ?
```
    phases = ['train', 'val', 'test'] if dataset in ['activitynet'] else ['train', 'test']
    for phase in phases:
        # load annotations
        with open(os.path.join(data_dir, phase + '.json')) as j:
            annos = json.load(j)
        time_meters['load_annotations'].update(time.time()-tictoc)
        tictoc = time.time()
```

**Comment by sangminwoo** [comment]
JSON files seem to be missing. I will provide JSON files soon.
Also, I'll try to put CLIP features on the drive if possible.
The description of the code structure may take a little longer because I need to review it again.

**Comment by aries-young** [comment]
> JSON files seem to be missing. I will provide JSON files soon. Also, I'll try to put CLIP features on the drive if possible. The description of the code structure may take a little longer because I need to review it again.

Thank you for your quick reply. I'm  looking forward to reproducing your work as soon as possible.

**Comment by sangminwoo** [comment]
JSON files are now uploaded.
