### ISSUE TITLE
No zero_shot_clip 

### ISSUE THREAD

**Issue by aries-young** [sangminwoo/Explore-And-Match#3]
In /lib/modeling/model.py, there is the following call for zero_shot_clip. However, there is no relevant content in the whole project.

`from lib.modeling.zero_shot_clip import build_zeroshot_clip`

**Comment by sangminwoo** [comment]
We had conducted experiments to verify the zero-shot capability of CLIP on the video grounding datasets, however, the results were omitted from the paper. So we decide not to provide relevant codes. Sorry for the confusion and please disregard those codes.

**Comment by aries-young** [comment]
> We had conducted experiments to verify the zero-shot capability of CLIP on the video grounding datasets, however, the results were omitted from the paper. So we decide not to provide relevant codes. Sorry for the confusion and please disregard those codes.

Thank you very much.
