### ISSUE TITLE
ap_array is empty

### ISSUE THREAD

**Issue by aries-young** [sangminwoo/Explore-And-Match#5]
I got this error during evaluating. I found sometimes ap_array was empty. Could you kind give some advice to adjust it?

```
  File "/Explore-and-Match/lib/evaluate/eval.py", line 75, in compute_ap
    iou_thd2ap = dict(zip([str(e) for e in iou_thds], ap_thds))
TypeError: 'numpy.float64' object is not iterable
```

**Comment by aries-young** [comment]
Hello, as for this problem, do you have some solution for me to reproduce this work ?

**Comment by sangminwoo** [comment]
Since there is no error in my case, It seems that modification of the code is causing the issue.
Please take a look at the code you have modified!

And if you need further help,  as the error message is too general, could you perhaps elaborate?

**Comment by aries-young** [comment]
> Since there is no error in my case, It seems that modification of the code is causing the issue. Please take a look at the code you have modified!
> 
> And if you need further help, as the error message is too general, could you perhaps elaborate?

Thank you so much. I'll check my code carefully. So sorry to bother you.

**Comment by sangminwoo** [comment]
No problem :)

**Comment by sunanhe** [comment]
I had the same problem. I found that this is due to the fact that there are not moments in "Long" length.

> https://github.com/sangminwoo/Explore-and-Match/blob/c07381affbad334e39793c4ca1563b45510e890e/lib/evaluate/eval.py#L135-L156

**Comment by aries-young** [comment]
> I had the same problem. I found that this is due to the fact that there are not moments in "Long" length.
> 
> > https://github.com/sangminwoo/Explore-and-Match/blob/c07381affbad334e39793c4ca1563b45510e890e/lib/evaluate/eval.py#L135-L156

Have you solved this problem?

**Comment by sangminwoo** [comment]
If you do not need to specify the length of time segments, maybe you can consider removing all the "range-related" codes and just run!

**Comment by minjoong507** [comment]
@aries-young @sunanhe I had the same error message too. Did you guys solve this problem?
