### ISSUE TITLE
Regarding Figure 7. on the paper.

### ISSUE THREAD

**Issue by vin30731** [sangminwoo/Explore-And-Match#6]
Hello,
Could you please explain more about fig.7 on the paper?
What does the x-axis and y-axis of the each proposals mean?
Thanks!

**Comment by sangminwoo** [comment]
Hi, @vin30731!
Thanks for your interest in our work!

A time segment can be represented as <start, end> or <center, width>.
In Figure 7, we showed 10 distributions of time segment predictions, each distribution belongs to a distinct learnable proposal.
Here, x-axis is center and y-axis is width.
If data points are in the top-middle, it means time segments are distributed around the center and their length is long.

I hope this explanation will resolve some ambiguity!

**Comment by vin30731** [comment]
Hi @sangminwoo, thanks for your prompt reply!
So the color of the graph is essentially the same as what y-axis represents?
They both represents the width of the proposal right?
Again, thank you for replying my questions, it is a great work.

**Comment by sangminwoo** [comment]
You're welcome! Here are the answers for the questions.

> So the color of the graph is essentially the same as what y-axis represents? YES!
> They both represents the width of the proposal right? YES!
