### ISSUE TITLE
'clip' Package in preprocess/clip_encoder.py

### ISSUE THREAD

**Issue by haojc** [sangminwoo/Explore-And-Match#7]
Thanks for your good work. When I extract the clip features for the datasets, I find the source code (preprocess/clip_encoder.py) imports a package named 'clip', which is not mentioned in Installation. Where can I install the 'clip' package? Thanks

**Comment by sangminwoo** [comment]
Hi! @haojc,
Thanks for your interest in our work!

We used official [CLIP package](https://github.com/openai/CLIP) for our clip_encoder.
All required packages can be downloaded by the following line.
``` pip install -r requirements.txt ```

hope this may resolve your problem.
Thanks!

**Comment by haojc** [comment]
Thank you very much! I didn't notice the requirments.txt
